CREATE DATABASE PnpStores 

CREATE TABLE Master_Pnp_Table (
       ProductID INT,
      Barcode VARCHAR (250),
      ProductName VARCHAR (250),
      Category VARCHAR (250),
      StoreID INT,
      StoreName VARCHAR (250),
      Province VARCHAR (250),
      CashierName VARCHAR (250),
      SaleDate DATETIME2,
      Quantity INT,
      UnitPrice DECIMAL (18,2),
      TotalAmount DECIMAL (18,2),
);

INSERT INTO Master_Pnp_Table
SELECT [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnpStores].[dbo].[1772032136184_pnp_sales_2025_01]
    UNION ALL
SELECT [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnpStores].[dbo].[1772032148926_pnp_sales_2025_02]
     UNION ALL
SELECT [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnpStores].[dbo].[1772032159369_pnp_sales_2025_03]
    UNION ALL
SELECT TOP (1000) [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnpStores].[dbo].[1772032170316_pnp_sales_2025_04]
     UNION ALL
SELECT [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnpStores].[dbo].[1772032179739_pnp_sales_2025_05]
   UNION ALL
SELECT [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnpStores].[dbo].[1772032189879_pnp_sales_2025_06]
    UNION ALL
SELECT [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
 FROM [PnpStores].[dbo].[1772032202072_pnp_sales_2025_07]
   UNION ALL
SELECT [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnpStores].[dbo].[1772032214258_pnp_sales_2025_08]
      UNION ALL
SELECT [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnpStores].[dbo].[1772032224900_pnp_sales_2025_09]
        UNION ALL
SELECT [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnpStores].[dbo].[1772032236969_pnp_sales_2025_10]
       UNION ALL
  SELECT TOP (1000) [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnpStores].[dbo].[1772032108507_pnp_sales_2025_11]
        UNION ALL
SELECT [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
FROM [PnpStores].[dbo].[1772032261154_pnp_sales_2025_12]

SELECT *
FROM Master_Pnp_Table